// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/competitions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Competitions"
                ],
                "summary": "Retrieve all competitions",
                "operationId": "get-competitions",
                "responses": {
                    "200": {
                        "description": "List of competitions",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.CompetitionResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Competitions"
                ],
                "summary": "Create a new competition",
                "operationId": "create-competition",
                "parameters": [
                    {
                        "description": "Competition details to create",
                        "name": "competition",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CompetitionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successful operation",
                        "schema": {
                            "$ref": "#/definitions/api.CompetitionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/competitions/{competitionID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Competitions"
                ],
                "summary": "Get a single competition by ID",
                "operationId": "get-competition",
                "parameters": [
                    {
                        "type": "string",
                        "default": "44dd315c-1abc-43aa-9843-642f920190d1",
                        "description": "UUID of the competition",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Competition found",
                        "schema": {
                            "$ref": "#/definitions/api.CompetitionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid competition ID",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Competitions"
                ],
                "summary": "Update an existing competition",
                "operationId": "update-competition",
                "parameters": [
                    {
                        "type": "string",
                        "default": "44dd315c-1abc-43aa-9843-642f920190d1",
                        "description": "UUID of the competition",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Competition details to update",
                        "name": "competition",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CompetitionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Competition updated",
                        "schema": {
                            "$ref": "#/definitions/api.CompetitionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Competitions"
                ],
                "summary": "Delete a competition",
                "operationId": "delete-competition",
                "parameters": [
                    {
                        "type": "string",
                        "default": "44dd315c-1abc-43aa-9843-642f920190d1",
                        "description": "UUID of the competition",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid competition ID",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/competitions/{competitionID}/seasons": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Seasons"
                ],
                "summary": "Retrieve all seasons for a competition",
                "operationId": "get-seasons",
                "parameters": [
                    {
                        "type": "string",
                        "default": "44dd315c-1abc-43aa-9843-642f920190d1",
                        "description": "Competition ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of seasons",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.SeasonResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Seasons"
                ],
                "summary": "Create a new season",
                "operationId": "create-season",
                "parameters": [
                    {
                        "type": "string",
                        "default": "44dd315c-1abc-43aa-9843-642f920190d1",
                        "description": "Competition ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Season details to create",
                        "name": "season",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SeasonRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successful operation",
                        "schema": {
                            "$ref": "#/definitions/api.SeasonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/competitions/{competitionID}/seasons/{seasonID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Seasons"
                ],
                "summary": "Get a single season by ID",
                "operationId": "get-season",
                "parameters": [
                    {
                        "type": "string",
                        "default": "44dd315c-1abc-43aa-9843-642f920190d1",
                        "description": "Competition ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "9300778f-cce0-4efe-af6c-e399d8170315",
                        "description": "Season ID",
                        "name": "seasonID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Season found",
                        "schema": {
                            "$ref": "#/definitions/api.SeasonResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid season ID",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Seasons"
                ],
                "summary": "Update an existing season",
                "operationId": "update-season",
                "parameters": [
                    {
                        "type": "string",
                        "default": "44dd315c-1abc-43aa-9843-642f920190d1",
                        "description": "Competition ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "9300778f-cce0-4efe-af6c-e399d8170315",
                        "description": "Season ID",
                        "name": "seasonID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Season details to update",
                        "name": "season",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SeasonRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Season updated",
                        "schema": {
                            "$ref": "#/definitions/api.SeasonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Seasons"
                ],
                "summary": "Delete a season by ID",
                "operationId": "delete-season",
                "parameters": [
                    {
                        "type": "string",
                        "default": "44dd315c-1abc-43aa-9843-642f920190d1",
                        "description": "Competition ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "9300778f-cce0-4efe-af6c-e399d8170315",
                        "description": "Season ID",
                        "name": "seasonID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content\"\t\"Season deleted successfully"
                    },
                    "400": {
                        "description": "Invalid season ID",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/competitions/{competitionID}/seasons/{seasonID}/games": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Get all games for a season",
                "operationId": "get-games",
                "parameters": [
                    {
                        "type": "string",
                        "default": "44dd315c-1abc-43aa-9843-642f920190d1",
                        "description": "Competition ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "9300778f-cce0-4efe-af6c-e399d8170315",
                        "description": "Season ID",
                        "name": "seasonID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of games",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.GameResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Create a new game",
                "operationId": "create-game",
                "parameters": [
                    {
                        "type": "string",
                        "default": "44dd315c-1abc-43aa-9843-642f920190d1",
                        "description": "Competition ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "9300778f-cce0-4efe-af6c-e399d8170315",
                        "description": "Season ID",
                        "name": "seasonID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Game details to create",
                        "name": "game",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GameRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successful operation",
                        "schema": {
                            "$ref": "#/definitions/api.GameResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/competitions/{competitionID}/seasons/{seasonID}/games/{gameID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Get a single game by ID",
                "operationId": "get-game",
                "parameters": [
                    {
                        "type": "string",
                        "default": "44dd315c-1abc-43aa-9843-642f920190d1",
                        "description": "Competition ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "9300778f-cce0-4efe-af6c-e399d8170315",
                        "description": "Season ID",
                        "name": "seasonID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "4019a7f3-7741-4d8f-b3e0-1c7f3a0a1a01",
                        "description": "Game ID",
                        "name": "gameID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Game found",
                        "schema": {
                            "$ref": "#/definitions/api.GameResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Update a game",
                "operationId": "update-game",
                "parameters": [
                    {
                        "type": "string",
                        "default": "44dd315c-1abc-43aa-9843-642f920190d1",
                        "description": "Competition ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "9300778f-cce0-4efe-af6c-e399d8170315",
                        "description": "Season ID",
                        "name": "seasonID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "4019a7f3-7741-4d8f-b3e0-1c7f3a0a1a01",
                        "description": "Game ID",
                        "name": "gameID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Game details to update",
                        "name": "game",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Game updated",
                        "schema": {
                            "$ref": "#/definitions/api.GameResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Delete a game by ID",
                "operationId": "delete-game",
                "parameters": [
                    {
                        "type": "string",
                        "default": "44dd315c-1abc-43aa-9843-642f920190d1",
                        "description": "Competition ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "9300778f-cce0-4efe-af6c-e399d8170315",
                        "description": "Season ID",
                        "name": "seasonID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "4019a7f3-7741-4d8f-b3e0-1c7f3a0a1a01",
                        "description": "Game ID",
                        "name": "gameID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content\"\t\"Game deleted successfully"
                    },
                    "400": {
                        "description": "Invalid game ID",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/teams": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Retrieve all teams",
                "operationId": "get-teams",
                "responses": {
                    "200": {
                        "description": "List of teams",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.TeamResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Create a new team",
                "operationId": "create-team",
                "parameters": [
                    {
                        "description": "Team details to create",
                        "name": "team",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TeamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successful operation",
                        "schema": {
                            "$ref": "#/definitions/api.TeamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/teams/{teamID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Get a single team by ID",
                "operationId": "get-team",
                "parameters": [
                    {
                        "type": "string",
                        "default": "013952a5-87e1-4d26-a312-09b2aff54241",
                        "description": "Team ID",
                        "name": "teamID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Team found",
                        "schema": {
                            "$ref": "#/definitions/api.TeamResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid team ID",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Update an existing team",
                "operationId": "update-team",
                "parameters": [
                    {
                        "type": "string",
                        "default": "013952a5-87e1-4d26-a312-09b2aff54241",
                        "description": "Team ID",
                        "name": "teamID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Team details to update",
                        "name": "team",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TeamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Team updated",
                        "schema": {
                            "$ref": "#/definitions/api.TeamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Delete a team by ID",
                "operationId": "delete-team",
                "parameters": [
                    {
                        "type": "string",
                        "default": "013952a5-87e1-4d26-a312-09b2aff54241",
                        "description": "Team ID",
                        "name": "teamID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content\"\t\"Team deleted successfully"
                    },
                    "400": {
                        "description": "Invalid team ID",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CompetitionRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                }
            }
        },
        "api.CompetitionResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.GameRequest": {
            "type": "object",
            "required": [
                "away_team_id",
                "date",
                "home_team_id",
                "stage_id"
            ],
            "properties": {
                "away_score": {
                    "type": "integer",
                    "minimum": 0
                },
                "away_team_id": {
                    "type": "string",
                    "example": "7b6cdb33-3bc6-4b0c-bac2-82d2a6bc6a97"
                },
                "date": {
                    "type": "string",
                    "example": "2025-08-02T00:00:00Z"
                },
                "home_score": {
                    "type": "integer",
                    "minimum": 0
                },
                "home_team_id": {
                    "type": "string",
                    "example": "013952a5-87e1-4d26-a312-09b2aff54241"
                },
                "stage_id": {
                    "type": "string",
                    "example": "eab15533-dea6-4a3d-8a95-d38e4fba2d5a"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.GameStatus"
                        }
                    ],
                    "example": "playing"
                }
            }
        },
        "api.GameResponse": {
            "type": "object",
            "properties": {
                "away_score": {
                    "type": "integer"
                },
                "away_team_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "home_score": {
                    "type": "integer"
                },
                "home_team_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "season_id": {
                    "type": "string"
                },
                "stage_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/api.GameStatus"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.GameStatus": {
            "type": "string",
            "enum": [
                "scheduled",
                "playing",
                "finished",
                "cancelled"
            ],
            "x-enum-varnames": [
                "GameStatusScheduled",
                "GameStatusPlaying",
                "GameStatusFinished",
                "GameStatusCancelled"
            ]
        },
        "api.SeasonRequest": {
            "type": "object",
            "required": [
                "end_date",
                "stages",
                "start_date",
                "teams"
            ],
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "2025-12-31T23:59:59Z"
                },
                "stages": {
                    "type": "array",
                    "maxItems": 50,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/api.StageRequest"
                    }
                },
                "start_date": {
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "teams": {
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 2,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "013952a5-87e1-4d26-a312-09b2aff54241",
                        "7b6cdb33-3bc6-4b0c-bac2-82d2a6bc6a97"
                    ]
                }
            }
        },
        "api.SeasonResponse": {
            "type": "object",
            "properties": {
                "competition_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "stages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.StageResponse"
                    }
                },
                "start_date": {
                    "type": "string"
                },
                "teams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.TeamResponse"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.StageRequest": {
            "type": "object",
            "required": [
                "name",
                "order_index",
                "stage_type"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "order_index": {
                    "type": "integer",
                    "minimum": 1
                },
                "stage_type": {
                    "$ref": "#/definitions/api.StageType"
                }
            }
        },
        "api.StageResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "order_index": {
                    "type": "integer"
                },
                "season_id": {
                    "type": "string"
                },
                "stage_type": {
                    "$ref": "#/definitions/api.StageType"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.StageType": {
            "type": "string",
            "enum": [
                "regular",
                "finals"
            ],
            "x-enum-varnames": [
                "StageTypeGroup",
                "StageTypeFinals"
            ]
        },
        "api.TeamRequest": {
            "type": "object",
            "required": [
                "abbreviation",
                "name"
            ],
            "properties": {
                "abbreviation": {
                    "type": "string",
                    "maxLength": 4,
                    "minLength": 2,
                    "example": "ABV"
                },
                "location": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                }
            }
        },
        "api.TeamResponse": {
            "type": "object",
            "properties": {
                "abbreviation": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Gainline Api",
	Description:      "A set of endpoints for managing gainline tasks",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
