DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS season_teams CASCADE;
DROP TABLE IF EXISTS stages CASCADE;
DROP TABLE IF EXISTS seasons CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS competitions CASCADE;

DROP TYPE IF EXISTS game_status;
DROP TYPE IF EXISTS stage_type;