networks:
  backend:

volumes:
  gainline-data:
    name: gainline-data
  ui-node-modules:

services:
  gainline-db:
    image: postgres:16
    container_name: gainline-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gainline
      POSTGRES_USER: gainline
      POSTGRES_PASSWORD: gainline
    volumes:
      - gainline-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gainline"]
      interval: 5s
      retries: 10

  gainline-redis:
    image: redis:7-alpine
    container_name: gainline-redis
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10

  gainline-migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      gainline-db:
        condition: service_healthy
    restart: "no"
    entrypoint:
      [
        "sh",
        "-c",
        "sleep 5 && migrate -path=/migrations -database=postgres://gainline:gainline@gainline-db:5432/gainline?sslmode=disable up",
      ]
    networks:
      - backend

  gainline-gamestate:
    container_name: gainline-gamestate
    build:
      context: .
      dockerfile: gamestate/Dockerfile
    depends_on:
      gainline-redis:
        condition: service_healthy
    ports:
      - "50051:50051"
    environment:
      PORT: 50051
      REDIS_HOST: gainline-redis
      REDIS_PORT: 6379
    networks:
      - backend
    restart: unless-stopped

  gainline-api:
    container_name: gainline-api
    build:
      context: ./api
    depends_on:
      gainline-db:
        condition: service_healthy
      gainline-gamestate:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      DB_HOST: gainline-db
      DB_PORT: 5432
      DB_USER: gainline
      DB_PASSWORD: gainline
      DB_DATABASE: gainline
      DB_SSL_MODE: disable
      PORT: 8080
      GAMESTATE_HOST: gainline-gamestate
      GAMESTATE_PORT: 50051
    networks:
      - backend
    restart: unless-stopped

  gainline-ui:
    container_name: gainline-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "4200:80" # maps container nginx port 80 to host 4200
    depends_on:
      - gainline-api
    networks:
      - backend
    restart: unless-stopped
