// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bradley-adams/gainline/db/db_handler (interfaces: DB,Queries)
//
// Generated by this command:
//
//	mockgen -destination=./db/db_handler/mock/db.go -package=mock_db github.com/bradley-adams/gainline/db/db_handler DB,Queries
//

// Package mock_db is a generated GoMock package.
package mock_db

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	db "github.com/bradley-adams/gainline/db/db"
	db_handler "github.com/bradley-adams/gainline/db/db_handler"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockDB) BeginTx(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, opts)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockDBMockRecorder) BeginTx(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockDB)(nil).BeginTx), ctx, opts)
}

// Commit mocks base method.
func (m *MockDB) Commit(tx *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockDBMockRecorder) Commit(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockDB)(nil).Commit), tx)
}

// ExecContext mocks base method.
func (m *MockDB) ExecContext(arg0 context.Context, arg1 string, arg2 ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecContext", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecContext indicates an expected call of ExecContext.
func (mr *MockDBMockRecorder) ExecContext(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecContext", reflect.TypeOf((*MockDB)(nil).ExecContext), varargs...)
}

// HealthCheck mocks base method.
func (m *MockDB) HealthCheck() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck")
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockDBMockRecorder) HealthCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockDB)(nil).HealthCheck))
}

// New mocks base method.
func (m *MockDB) New(arg0 db.DBTX) db_handler.Queries {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", arg0)
	ret0, _ := ret[0].(db_handler.Queries)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockDBMockRecorder) New(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockDB)(nil).New), arg0)
}

// PrepareContext mocks base method.
func (m *MockDB) PrepareContext(arg0 context.Context, arg1 string) (*sql.Stmt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareContext", arg0, arg1)
	ret0, _ := ret[0].(*sql.Stmt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareContext indicates an expected call of PrepareContext.
func (mr *MockDBMockRecorder) PrepareContext(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareContext", reflect.TypeOf((*MockDB)(nil).PrepareContext), arg0, arg1)
}

// QueryContext mocks base method.
func (m *MockDB) QueryContext(arg0 context.Context, arg1 string, arg2 ...any) (*sql.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryContext", varargs...)
	ret0, _ := ret[0].(*sql.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryContext indicates an expected call of QueryContext.
func (mr *MockDBMockRecorder) QueryContext(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryContext", reflect.TypeOf((*MockDB)(nil).QueryContext), varargs...)
}

// QueryRowContext mocks base method.
func (m *MockDB) QueryRowContext(arg0 context.Context, arg1 string, arg2 ...any) *sql.Row {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRowContext", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// QueryRowContext indicates an expected call of QueryRowContext.
func (mr *MockDBMockRecorder) QueryRowContext(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRowContext", reflect.TypeOf((*MockDB)(nil).QueryRowContext), varargs...)
}

// Rollback mocks base method.
func (m *MockDB) Rollback(tx *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockDBMockRecorder) Rollback(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockDB)(nil).Rollback), tx)
}

// MockQueries is a mock of Queries interface.
type MockQueries struct {
	ctrl     *gomock.Controller
	recorder *MockQueriesMockRecorder
	isgomock struct{}
}

// MockQueriesMockRecorder is the mock recorder for MockQueries.
type MockQueriesMockRecorder struct {
	mock *MockQueries
}

// NewMockQueries creates a new mock instance.
func NewMockQueries(ctrl *gomock.Controller) *MockQueries {
	mock := &MockQueries{ctrl: ctrl}
	mock.recorder = &MockQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueries) EXPECT() *MockQueriesMockRecorder {
	return m.recorder
}

// CreateCompetition mocks base method.
func (m *MockQueries) CreateCompetition(ctx context.Context, arg db.CreateCompetitionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCompetition", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCompetition indicates an expected call of CreateCompetition.
func (mr *MockQueriesMockRecorder) CreateCompetition(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCompetition", reflect.TypeOf((*MockQueries)(nil).CreateCompetition), ctx, arg)
}

// CreateGame mocks base method.
func (m *MockQueries) CreateGame(ctx context.Context, arg db.CreateGameParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGame", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGame indicates an expected call of CreateGame.
func (mr *MockQueriesMockRecorder) CreateGame(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGame", reflect.TypeOf((*MockQueries)(nil).CreateGame), ctx, arg)
}

// CreateSeason mocks base method.
func (m *MockQueries) CreateSeason(ctx context.Context, arg db.CreateSeasonParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSeason", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSeason indicates an expected call of CreateSeason.
func (mr *MockQueriesMockRecorder) CreateSeason(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSeason", reflect.TypeOf((*MockQueries)(nil).CreateSeason), ctx, arg)
}

// CreateSeasonTeams mocks base method.
func (m *MockQueries) CreateSeasonTeams(ctx context.Context, arg db.CreateSeasonTeamsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSeasonTeams", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSeasonTeams indicates an expected call of CreateSeasonTeams.
func (mr *MockQueriesMockRecorder) CreateSeasonTeams(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSeasonTeams", reflect.TypeOf((*MockQueries)(nil).CreateSeasonTeams), ctx, arg)
}

// CreateStage mocks base method.
func (m *MockQueries) CreateStage(ctx context.Context, arg db.CreateStageParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStage", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStage indicates an expected call of CreateStage.
func (mr *MockQueriesMockRecorder) CreateStage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStage", reflect.TypeOf((*MockQueries)(nil).CreateStage), ctx, arg)
}

// CreateTeam mocks base method.
func (m *MockQueries) CreateTeam(ctx context.Context, arg db.CreateTeamParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockQueriesMockRecorder) CreateTeam(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockQueries)(nil).CreateTeam), ctx, arg)
}

// DeleteCompetition mocks base method.
func (m *MockQueries) DeleteCompetition(ctx context.Context, arg db.DeleteCompetitionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCompetition", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCompetition indicates an expected call of DeleteCompetition.
func (mr *MockQueriesMockRecorder) DeleteCompetition(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCompetition", reflect.TypeOf((*MockQueries)(nil).DeleteCompetition), ctx, arg)
}

// DeleteGame mocks base method.
func (m *MockQueries) DeleteGame(ctx context.Context, arg db.DeleteGameParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGame", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGame indicates an expected call of DeleteGame.
func (mr *MockQueriesMockRecorder) DeleteGame(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGame", reflect.TypeOf((*MockQueries)(nil).DeleteGame), ctx, arg)
}

// DeleteGamesByCompetitionID mocks base method.
func (m *MockQueries) DeleteGamesByCompetitionID(ctx context.Context, arg db.DeleteGamesByCompetitionIDParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGamesByCompetitionID", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGamesByCompetitionID indicates an expected call of DeleteGamesByCompetitionID.
func (mr *MockQueriesMockRecorder) DeleteGamesByCompetitionID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGamesByCompetitionID", reflect.TypeOf((*MockQueries)(nil).DeleteGamesByCompetitionID), ctx, arg)
}

// DeleteGamesBySeasonID mocks base method.
func (m *MockQueries) DeleteGamesBySeasonID(ctx context.Context, arg db.DeleteGamesBySeasonIDParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGamesBySeasonID", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGamesBySeasonID indicates an expected call of DeleteGamesBySeasonID.
func (mr *MockQueriesMockRecorder) DeleteGamesBySeasonID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGamesBySeasonID", reflect.TypeOf((*MockQueries)(nil).DeleteGamesBySeasonID), ctx, arg)
}

// DeleteSeason mocks base method.
func (m *MockQueries) DeleteSeason(ctx context.Context, arg db.DeleteSeasonParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSeason", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSeason indicates an expected call of DeleteSeason.
func (mr *MockQueriesMockRecorder) DeleteSeason(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSeason", reflect.TypeOf((*MockQueries)(nil).DeleteSeason), ctx, arg)
}

// DeleteSeasonTeam mocks base method.
func (m *MockQueries) DeleteSeasonTeam(ctx context.Context, arg db.DeleteSeasonTeamParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSeasonTeam", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSeasonTeam indicates an expected call of DeleteSeasonTeam.
func (mr *MockQueriesMockRecorder) DeleteSeasonTeam(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSeasonTeam", reflect.TypeOf((*MockQueries)(nil).DeleteSeasonTeam), ctx, arg)
}

// DeleteSeasonTeamsBySeasonID mocks base method.
func (m *MockQueries) DeleteSeasonTeamsBySeasonID(ctx context.Context, arg db.DeleteSeasonTeamsBySeasonIDParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSeasonTeamsBySeasonID", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSeasonTeamsBySeasonID indicates an expected call of DeleteSeasonTeamsBySeasonID.
func (mr *MockQueriesMockRecorder) DeleteSeasonTeamsBySeasonID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSeasonTeamsBySeasonID", reflect.TypeOf((*MockQueries)(nil).DeleteSeasonTeamsBySeasonID), ctx, arg)
}

// DeleteSeasonsByCompetitionID mocks base method.
func (m *MockQueries) DeleteSeasonsByCompetitionID(ctx context.Context, arg db.DeleteSeasonsByCompetitionIDParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSeasonsByCompetitionID", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSeasonsByCompetitionID indicates an expected call of DeleteSeasonsByCompetitionID.
func (mr *MockQueriesMockRecorder) DeleteSeasonsByCompetitionID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSeasonsByCompetitionID", reflect.TypeOf((*MockQueries)(nil).DeleteSeasonsByCompetitionID), ctx, arg)
}

// DeleteTeam mocks base method.
func (m *MockQueries) DeleteTeam(ctx context.Context, arg db.DeleteTeamParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeam", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTeam indicates an expected call of DeleteTeam.
func (mr *MockQueriesMockRecorder) DeleteTeam(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeam", reflect.TypeOf((*MockQueries)(nil).DeleteTeam), ctx, arg)
}

// GetCompetition mocks base method.
func (m *MockQueries) GetCompetition(ctx context.Context, id uuid.UUID) (db.Competition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompetition", ctx, id)
	ret0, _ := ret[0].(db.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompetition indicates an expected call of GetCompetition.
func (mr *MockQueriesMockRecorder) GetCompetition(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompetition", reflect.TypeOf((*MockQueries)(nil).GetCompetition), ctx, id)
}

// GetCompetitions mocks base method.
func (m *MockQueries) GetCompetitions(ctx context.Context) ([]db.Competition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompetitions", ctx)
	ret0, _ := ret[0].([]db.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompetitions indicates an expected call of GetCompetitions.
func (mr *MockQueriesMockRecorder) GetCompetitions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompetitions", reflect.TypeOf((*MockQueries)(nil).GetCompetitions), ctx)
}

// GetGame mocks base method.
func (m *MockQueries) GetGame(ctx context.Context, id uuid.UUID) (db.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGame", ctx, id)
	ret0, _ := ret[0].(db.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGame indicates an expected call of GetGame.
func (mr *MockQueriesMockRecorder) GetGame(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGame", reflect.TypeOf((*MockQueries)(nil).GetGame), ctx, id)
}

// GetGames mocks base method.
func (m *MockQueries) GetGames(ctx context.Context, seasonID uuid.UUID) ([]db.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGames", ctx, seasonID)
	ret0, _ := ret[0].([]db.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGames indicates an expected call of GetGames.
func (mr *MockQueriesMockRecorder) GetGames(ctx, seasonID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGames", reflect.TypeOf((*MockQueries)(nil).GetGames), ctx, seasonID)
}

// GetSeason mocks base method.
func (m *MockQueries) GetSeason(ctx context.Context, id uuid.UUID) (db.Season, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeason", ctx, id)
	ret0, _ := ret[0].(db.Season)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeason indicates an expected call of GetSeason.
func (mr *MockQueriesMockRecorder) GetSeason(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeason", reflect.TypeOf((*MockQueries)(nil).GetSeason), ctx, id)
}

// GetSeasonTeams mocks base method.
func (m *MockQueries) GetSeasonTeams(ctx context.Context, seasonID uuid.UUID) ([]db.GetSeasonTeamsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeasonTeams", ctx, seasonID)
	ret0, _ := ret[0].([]db.GetSeasonTeamsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeasonTeams indicates an expected call of GetSeasonTeams.
func (mr *MockQueriesMockRecorder) GetSeasonTeams(ctx, seasonID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeasonTeams", reflect.TypeOf((*MockQueries)(nil).GetSeasonTeams), ctx, seasonID)
}

// GetSeasons mocks base method.
func (m *MockQueries) GetSeasons(ctx context.Context, competitionID uuid.UUID) ([]db.Season, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeasons", ctx, competitionID)
	ret0, _ := ret[0].([]db.Season)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeasons indicates an expected call of GetSeasons.
func (mr *MockQueriesMockRecorder) GetSeasons(ctx, competitionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeasons", reflect.TypeOf((*MockQueries)(nil).GetSeasons), ctx, competitionID)
}

// GetStagesBySeasonID mocks base method.
func (m *MockQueries) GetStagesBySeasonID(ctx context.Context, id uuid.UUID) ([]db.Stage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStagesBySeasonID", ctx, id)
	ret0, _ := ret[0].([]db.Stage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStagesBySeasonID indicates an expected call of GetStagesBySeasonID.
func (mr *MockQueriesMockRecorder) GetStagesBySeasonID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStagesBySeasonID", reflect.TypeOf((*MockQueries)(nil).GetStagesBySeasonID), ctx, id)
}

// GetTeam mocks base method.
func (m *MockQueries) GetTeam(ctx context.Context, id uuid.UUID) (db.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", ctx, id)
	ret0, _ := ret[0].(db.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockQueriesMockRecorder) GetTeam(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockQueries)(nil).GetTeam), ctx, id)
}

// GetTeams mocks base method.
func (m *MockQueries) GetTeams(ctx context.Context) ([]db.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeams", ctx)
	ret0, _ := ret[0].([]db.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeams indicates an expected call of GetTeams.
func (mr *MockQueriesMockRecorder) GetTeams(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeams", reflect.TypeOf((*MockQueries)(nil).GetTeams), ctx)
}

// UpdateCompetition mocks base method.
func (m *MockQueries) UpdateCompetition(ctx context.Context, arg db.UpdateCompetitionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompetition", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCompetition indicates an expected call of UpdateCompetition.
func (mr *MockQueriesMockRecorder) UpdateCompetition(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompetition", reflect.TypeOf((*MockQueries)(nil).UpdateCompetition), ctx, arg)
}

// UpdateGame mocks base method.
func (m *MockQueries) UpdateGame(ctx context.Context, arg db.UpdateGameParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGame", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGame indicates an expected call of UpdateGame.
func (mr *MockQueriesMockRecorder) UpdateGame(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGame", reflect.TypeOf((*MockQueries)(nil).UpdateGame), ctx, arg)
}

// UpdateSeason mocks base method.
func (m *MockQueries) UpdateSeason(ctx context.Context, arg db.UpdateSeasonParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSeason", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSeason indicates an expected call of UpdateSeason.
func (mr *MockQueriesMockRecorder) UpdateSeason(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSeason", reflect.TypeOf((*MockQueries)(nil).UpdateSeason), ctx, arg)
}

// UpdateTeam mocks base method.
func (m *MockQueries) UpdateTeam(ctx context.Context, arg db.UpdateTeamParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeam", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTeam indicates an expected call of UpdateTeam.
func (mr *MockQueriesMockRecorder) UpdateTeam(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeam", reflect.TypeOf((*MockQueries)(nil).UpdateTeam), ctx, arg)
}
