apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  DB_DATABASE: {{ .Values.config.dbDatabase | quote }}
  DB_SSL_MODE: {{ .Values.config.dbSslMode | quote }}
  PORT: {{ .Values.config.port | quote }}
  GAMESTATE_HOST: {{ .Values.config.gamestateHost | quote }}
  GAMESTATE_PORT: {{ .Values.config.gamestatePort | quote }}