apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: migrate
          image: {{ .Values.migrate.image.repository }}:{{ .Values.migrate.image.tag }}
          args:
            - "-path=/migrations"
            - "-database=postgres://{{ .Values.config.dbUser }}:$(DB_PASSWORD)@{{ .Values.config.dbHost }}:{{ .Values.config.dbPort }}/{{ .Values.config.dbDatabase }}?sslmode={{ .Values.config.dbSslMode }}"
            - "up"
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: db-password
          volumeMounts:
            - name: db-password
              mountPath: "/mnt/secrets"
              readOnly: true
      volumes:
        - name: db-password
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Release.Name }}-db-password